# Generated by Django 4.2.4 on 2023-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wenyeji", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
    ]
